baseurl: "https://ltchin.github.io/"
languageCode: "en-us"
title: "Lilly Chin"
# theme: "ltchin-port"
# googleAnalytics: ""
# disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

menu:
  main:
    - name: CV
      url: "/files/lillychin-cv.pdf"
      weight: 1
    - name: Research
      url: "research/"
      weight: 2
    - name: Projects
      url: "projects/"
      weight: 3
    - name: Crafting
      url: "crafting/"
      parent: "Projects"
      weight: 4
    - name: Making
      url: "making/"
      parent: "Projects"
      weight: 4
    - name: Writing
      url: "writing/"
      parent: "Projects"
      weight: 4
    - name: Press
      url: "press/"
      weight: 6

params:
  description: "Lilly Chin's website"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
      endLevel: 4
      ordered: false
      startLevel: 2

