baseurl: "/"
languageCode: "en-us"
title: "Lilly Chin"
# theme: "ltchin-port"
# googleAnalytics: ""
# disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
publishdir: "docs"

menu:
  main:
    - name: CV
      url: "/files/lillychin-cv.pdf"
      weight: 1
    - name: Research
      url: "research/"
      weight: 2
    - name: MERGe Lab
      url: "https://merge-lab.github.io/research/"
      parent: "Research"
      weight: 2
    - name: Philosophy
      url: "research/philosophy/"
      parent: "Research"
      weight: 3
    - name: Inspiration
      url: "research/who-taught-me/"
      parent: "Research"
      weight: 4
    # - name: Teaching
    #   url: "teaching/"
    #   weight: 3
    - name: Projects
      url: "projects/"
      weight: 4
    - name: Crafting
      url: "projects/crafting/"
      parent: "Projects"
      weight: 5
    - name: Making
      url: "projects/making/"
      parent: "Projects"
      weight: 5
    - name: Writing
      url: "projects/writing/"
      parent: "Projects"
      weight: 5
    - name: Press
      url: "press/"
      weight: 6

params:
  description: "Lilly Chin's website"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
      endLevel: 4
      ordered: false
      startLevel: 2

